name: Deploy to GitHub Pages

on:
  push:
    branches:
      - develop

permissions:
  contents: read  # Necessary to read contents from the repository
  id-token: write  # Grant permission to request ID tokens for authentication

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the website
        run: |
          npx parcel build src/index.html --dist-dir dist

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
